<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ajay-singh-lodhi" failures="2" tests="30" name="TestScript.NotifyTest" time="939.763" errors="1" timestamp="2024-04-22T14:39:41 IST" skipped="0">
  <testcase classname="TestScript.NotifyTest" name="Login" time="18.619"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Click_On_Utilities" time="24.995"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Empty_Notify_Msgs" time="25.386"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Enter_Valid_Search_In_Notify_Msgs" time="27.160">
    <failure message="test case pass expected [Test] but found [test]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test case pass expected [Test] but found [test]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at Pages.Notifypage.Valid_Search(Notifypage.java:102)
at TestScript.NotifyTest.Enter_Valid_Search_In_Notify_Msgs(NotifyTest.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Enter_Valid_Search_In_Notify_Msgs -->
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Enter_InValid_Search_In_Notify_Msgs" time="28.426"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="All_Users_In_Notify" time="26.801"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Priority_In_Notify" time="27.610"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Set_Regular_In_Notify" time="28.703"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Set_Time_Sensitive_In_Notify" time="27.497"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Set_Urgent_In_Notify" time="27.183"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Set_SOS_In_Notify" time="28.432"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Click_On_Create_New_In_Notify" time="26.744"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Click_On_Send_Button_Without_Entering_Msg_In_Notify" time="30.849"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Click_On_Send_Button_With_Entering_Msg_In_Notify" time="30.617"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Search_Valid_User_In_Notify" time="29.594"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Search_InValid_User_In_Notify" time="29.045"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Validate_Users_Count" time="29.916">
    <failure message="test case pass expected [129] but found [130]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test case pass expected [129] but found [130]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at Pages.Notifypage.Validate_User_Count(Notifypage.java:304)
at TestScript.NotifyTest.Validate_Users_Count(NotifyTest.java:728)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Validate_Users_Count -->
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Validate_Groups_Count" time="30.643"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Validate_Selected_Users_Groups_Count" time="29.345"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_The_Notify_Msg_To_User" time="34.979"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_The_Notify_Msg_To_Group" time="38.631"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_The_Notify_Msg_To_User_Group" time="38.692"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Search_Valid_User_Or_Group_In_Selected_Members" time="38.650"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Search_Invalid_User_Or_Group_In_Selected_Members" time="37.987"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_Regular_Notify_Msg" time="41.353"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_Time_Sensitive_Notify_Msg" time="42.505"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_Urgent_Notify_Msg" time="44.624"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_SOS_Notify_Msg_With_Confirmation_Text_No_Button" time="43.052"/>
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Send_SOS_Notify_Msg_With_Confirmation_Text_Yes_Button" time="25.081">
    <error message="no such element: Unable to locate element: {&quot;method&quot;:&quot;xpath&quot;,&quot;selector&quot;:&quot;//div[@class=&#039;add-btn&#039;]				&quot;}
  (Session info: chrome=107.0.5304.87)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &#039;4.11.0&#039;, revision: &#039;040bc5406b&#039;
System info: os.name: &#039;Linux&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;4.15.0-197-generic&#039;, java.version: &#039;17.0.10&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2daa07e715f52cc3cf54db31fcb625e, findElement {using=xpath, value=//div[@class=&#039;add-btn&#039;]				}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.d0LCa0}, goog:chromeOptions: {debuggerAddress: localhost:38989}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:38989/devtoo..., se:cdpVersion: 107.0.5304.87, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: d2daa07e715f52cc3cf54db31fcb625e" type="org.openqa.selenium.NoSuchElementException">
      <![CDATA[org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='add-btn']"}
  (Session info: chrome=107.0.5304.87)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-197-generic', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2daa07e715f52cc3cf54db31fcb625e, findElement {using=xpath, value=//div[@class='add-btn']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 107.0.5304.87, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: /tmp/.com.google.Chrome.d0LCa0}, goog:chromeOptions: {debuggerAddress: localhost:38989}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:cdp: ws://localhost:38989/devtoo..., se:cdpVersion: 107.0.5304.87, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: d2daa07e715f52cc3cf54db31fcb625e
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:52)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:191)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:349)
at Pages.Notifypage.Validate_Login(Notifypage.java:56)
at TestScript.NotifyTest.Send_SOS_Notify_Msg_With_Confirmation_Text_Yes_Button(NotifyTest.java:1605)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Send_SOS_Notify_Msg_With_Confirmation_Text_Yes_Button -->
  <system-out/>
  <testcase classname="TestScript.NotifyTest" name="Recall_Notify_Msg" time="26.644"/>
  <system-out/>
</testsuite> <!-- TestScript.NotifyTest -->
