<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ajay-singh-lodhi" failures="2" tests="14" name="TestScript.BridgecallTest" time="364.580" errors="0" timestamp="2024-04-23T15:44:14 IST" skipped="0">
  <testcase classname="TestScript.BridgecallTest" name="Login" time="15.479"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Bridge_Call_In_Utilites" time="22.960"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Create_New" time="25.954"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Invite_Without_Entering_Title" time="32.021"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Invite_With_Entering_Only_Title" time="27.898"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Invite_With_Selecting_Only_User" time="29.484"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Search_Valid_User_In_Members" time="24.374">
    <failure message="test case pass expected [128] but found [129]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test case pass expected [128] but found [129]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at Pages.Bridgecallpage.Members_Count(Bridgecallpage.java:214)
at TestScript.BridgecallTest.Search_Valid_User_In_Members(BridgecallTest.java:343)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Search_Valid_User_In_Members -->
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Search_Invalid_User_In_Members" time="23.753">
    <failure message="test case pass expected [128] but found [129]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: test case pass expected [128] but found [129]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at Pages.Bridgecallpage.Members_Count(Bridgecallpage.java:214)
at TestScript.BridgecallTest.Search_Invalid_User_In_Members(BridgecallTest.java:400)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Search_Invalid_User_In_Members -->
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Search_Valid_User_In_Selected_Members" time="28.315"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Search_Invalid_User_In_Selected_Members" time="28.849"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Deselect_The_Enable_Waiting_Room" time="26.774"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Deselect_The_Allow_Others_To_Invite" time="26.364"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Click_On_Invite_By_Entering_Details" time="29.851"/>
  <system-out/>
  <testcase classname="TestScript.BridgecallTest" name="Validate_The_Call_In_Bridge_Call" time="22.504"/>
  <system-out/>
</testsuite> <!-- TestScript.BridgecallTest -->
